//
//  PreviewData.swift
//  ParentGuide
//

import Foundation

enum PreviewData {

    // MARK: - Real March 2026 Events from orangecountyparentguide.com

    static let sampleEvents: [Event] = [

        // MARK: Festivals & Major Events

        Event(id: "bubblefest", title: "Bubblefest at Discovery Cube", eventDescription: "Annual spring tradition featuring the Mega Bubblefest Laser Show, interactive Bubble Zone with hands-on science activities, and world-class bubble artistry by the Yang family.", startDate: makeDate(2026, 3, 14, 10, 0), endDate: makeDate(2026, 3, 14, 17, 0), isAllDay: false, category: .museum, city: "Santa Ana", address: "2500 N Main St, Santa Ana, CA 92705", latitude: 33.7455, longitude: -117.8677, locationName: "Discovery Cube Orange County", imageURL: "https://www.discoverycube.org/wp-content/uploads/2026/02/G-9494-DCOC-Bubblefest-Homepage-Banners-2-1.jpg", externalURL: "https://www.discoverycube.org/", isFeatured: true, isRecurring: false, tags: ["science", "indoor", "kids"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "boysenberry", title: "Knott's Boysenberry Festival", eventDescription: "Annual spring festival featuring over 100 boysenberry-inspired food and drink items, live entertainment, artisan crafts, and family-friendly activities. Included with park admission.", startDate: makeDate(2026, 3, 13, 10, 0), endDate: makeDate(2026, 3, 13, 18, 0), isAllDay: false, category: .festival, city: "Buena Park", address: "8039 Beach Blvd, Buena Park, CA 90620", latitude: 33.8443, longitude: -118.0003, locationName: "Knott's Berry Farm", imageURL: "https://cdn.sanity.io/images/bsnrdz4t/production/e16bec2300ef3a1c7322f047e26ee07770f63988-1400x560.jpg?w=1200&h=627&fit=crop&auto=format", externalURL: "https://www.knotts.com", isFeatured: true, isRecurring: false, tags: ["food", "festival", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "whales-sat", title: "Dana Point Festival of Whales", eventDescription: "Annual coastal festival celebrating migratory whales with whale-watching excursions, a parade, chowder cook-off, sand sculpture competitions, educational exhibits, and family-friendly marine entertainment.", startDate: makeDate(2026, 3, 7, 10, 0), endDate: makeDate(2026, 3, 7, 17, 0), isAllDay: false, category: .festival, city: "Dana Point", address: "34675 Golden Lantern, Dana Point, CA 92629", latitude: 33.4597, longitude: -117.6983, locationName: "Dana Point Harbor", imageURL: "https://festivalofwhales.com/wp-content/uploads/2026/01/FOW1.jpg", externalURL: "https://festivalofwhales.com/", isFeatured: true, isRecurring: false, tags: ["outdoor", "free", "festival", "ocean"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "swallows", title: "Swallows Day Parade & Mercado Street Fair", eventDescription: "Annual Old West-style parade celebrating the return of the swallows to Mission San Juan Capistrano. Features the Mercado Street Fair with food, entertainment, and family activities. Free and dog-friendly.", startDate: makeDate(2026, 3, 21, 11, 0), endDate: makeDate(2026, 3, 21, 15, 0), isAllDay: false, category: .festival, city: "San Juan Capistrano", address: "Camino Capistrano, San Juan Capistrano, CA 92675", latitude: 33.5017, longitude: -117.6628, locationName: "Downtown San Juan Capistrano", imageURL: "https://swallowsdayparade.org/wp-content/uploads/2023/05/Parade-02-2.jpg", externalURL: "https://swallowsdayparade.org/", isFeatured: true, isRecurring: false, tags: ["free", "outdoor", "parade", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "restaurant-week", title: "OC Restaurant Week", eventDescription: "A one-week dining adventure with over 150 participating restaurants offering prix-fixe menus across Orange County. Lunch from $15, Dinner from $25. No tickets or passes required.", startDate: makeDate(2026, 3, 8, 11, 0), endDate: makeDate(2026, 3, 14, 22, 0), isAllDay: false, category: .food, city: "Orange County", address: nil, latitude: 33.7175, longitude: -117.8311, locationName: "Various Restaurants", imageURL: "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,f_jpg,h_716,q_75,w_639/v1/clients/surfcityusa/QUw0Xeqb_72099ac2-5348-4aaf-8c11-f19d9daad045.jpg", externalURL: "https://ocrestaurantweek.com/", isFeatured: true, isRecurring: false, tags: ["food", "dining", "deals"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        // MARK: Kite Party

        Event(id: "kite-party-sat", title: "Kite Party at Huntington Beach", eventDescription: "Free annual kite festival attracting performers, designers, and enthusiasts to Huntington Beach Pier. Features world-class kite flying demonstrations and family-friendly beach activities.", startDate: makeDate(2026, 3, 7, 8, 0), endDate: makeDate(2026, 3, 7, 17, 0), isAllDay: false, category: .outdoorAdventure, city: "Huntington Beach", address: "200 Pacific Coast Hwy, Huntington Beach, CA 92648", latitude: 33.6553, longitude: -117.9992, locationName: "Huntington Beach Pier", imageURL: "https://assets.simpleviewinc.com/simpleview/image/upload/v1573075654/clients/surfcityusa/DJI_0387_1__2a9cbdab-8c22-4a75-bc70-ff743394f11d.jpg", externalURL: "https://kiteparty.com/", isFeatured: true, isRecurring: false, tags: ["free", "outdoor", "beach", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "kite-party-sun", title: "Kite Party at Huntington Beach", eventDescription: "Free annual kite festival attracting performers, designers, and enthusiasts to Huntington Beach Pier. Features world-class kite flying demonstrations and family-friendly beach activities.", startDate: makeDate(2026, 3, 8, 8, 0), endDate: makeDate(2026, 3, 8, 17, 0), isAllDay: false, category: .outdoorAdventure, city: "Huntington Beach", address: "200 Pacific Coast Hwy, Huntington Beach, CA 92648", latitude: 33.6553, longitude: -117.9992, locationName: "Huntington Beach Pier", imageURL: "https://assets.simpleviewinc.com/simpleview/image/upload/v1573075654/clients/surfcityusa/DJI_0387_1__2a9cbdab-8c22-4a75-bc70-ff743394f11d.jpg", externalURL: "https://kiteparty.com/", isFeatured: false, isRecurring: false, tags: ["free", "outdoor", "beach", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        // MARK: Food Events

        Event(id: "pancake-day", title: "IHOP Free Pancake Day", eventDescription: "IHOP offers a free short stack of three buttermilk pancakes at participating locations nationwide while supplies last. Donations accepted for local charities.", startDate: makeDate(2026, 3, 3, 7, 0), endDate: makeDate(2026, 3, 3, 20, 0), isAllDay: false, category: .food, city: "Santa Ana", address: "1001 E 17th St, Santa Ana, CA 92701", latitude: 33.7515, longitude: -117.8466, locationName: "IHOP", imageURL: "https://upload.wikimedia.org/wikipedia/commons/d/d6/The_exterior_of_a_modern_IHOP_restaurant_in_Greenville%2C_South_Carolina_02.jpg", externalURL: "https://www.ihop.com/", isFeatured: false, isRecurring: false, tags: ["free", "food", "kids"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "cfa-playdate", title: "Chick-Fil-A Family Play Date", eventDescription: "Bring the kids for a casual play date at Chick-fil-A with an indoor playground. Enjoy lunch while the little ones play and socialize with other families.", startDate: makeDate(2026, 3, 12, 10, 0), endDate: makeDate(2026, 3, 12, 12, 0), isAllDay: false, category: .food, city: "Irvine", address: "13682 Jamboree Rd, Irvine, CA 92602", latitude: 33.6973, longitude: -117.7990, locationName: "Chick-fil-A - The Market Place", imageURL: "https://upload.wikimedia.org/wikipedia/commons/9/98/Restaurant_Chick-Fil-A_in_Sugar_House_SLC.JPG", externalURL: "https://www.chick-fil-a.com/", isFeatured: false, isRecurring: true, tags: ["food", "indoor", "toddler", "free"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        // MARK: Museums & Free Admission

        Event(id: "museums-on-us", title: "Bank of America Museums on Us", eventDescription: "Bank of America cardholders receive free general admission at Discovery Cube OC and Laguna Art Museum. Show your BofA card and photo ID at the door.", startDate: makeDate(2026, 3, 7, 10, 0), endDate: makeDate(2026, 3, 7, 17, 0), isAllDay: false, category: .museum, city: "Santa Ana", address: "2500 N Main St, Santa Ana, CA 92705", latitude: 33.7455, longitude: -117.8677, locationName: "Discovery Cube Orange County", imageURL: "https://www.discoverycube.org/wp-content/uploads/2026/02/G-9494-DCOC-Bubblefest-Homepage-Banners-2-1.jpg", externalURL: "https://about.bankofamerica.com/", isFeatured: false, isRecurring: false, tags: ["free", "museum", "indoor"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "pretend-city-discovery", title: "Discovery Day at Pretend City", eventDescription: "Half-price admission for families! Explore the interactive children's museum with 17 interconnected rooms designed for kids to learn through imaginative play.", startDate: makeDate(2026, 3, 6, 10, 0), endDate: makeDate(2026, 3, 6, 17, 0), isAllDay: false, category: .museum, city: "Irvine", address: "29 Hubble, Irvine, CA 92618", latitude: 33.6846, longitude: -117.8265, locationName: "Pretend City Children's Museum", imageURL: "https://upload.wikimedia.org/wikipedia/commons/6/60/Pretend-city-front.jpg", externalURL: "https://www.pretendcity.org/", isFeatured: false, isRecurring: false, tags: ["discount", "indoor", "museum", "kids"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        // MARK: Toddler Activities

        Event(id: "toddler-town-mar9", title: "Toddler Town at Pretend City", eventDescription: "The museum opens just for toddlers ages 19 months to 3 years. Kids can climb, dance, problem-solve, and pretend through a miniature world supporting developmental milestones.", startDate: makeDate(2026, 3, 9, 8, 0), endDate: makeDate(2026, 3, 9, 9, 30), isAllDay: false, category: .toddlerActivity, city: "Irvine", address: "29 Hubble, Irvine, CA 92618", latitude: 33.6846, longitude: -117.8265, locationName: "Pretend City Children's Museum", imageURL: "https://upload.wikimedia.org/wikipedia/commons/6/60/Pretend-city-front.jpg", externalURL: "https://www.pretendcity.org/", isFeatured: false, isRecurring: true, tags: ["toddler", "indoor", "museum"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "toddler-town-mar16", title: "Toddler Town at Pretend City", eventDescription: "The museum opens just for toddlers ages 19 months to 3 years. Kids can climb, dance, problem-solve, and pretend through a miniature world supporting developmental milestones.", startDate: makeDate(2026, 3, 16, 8, 0), endDate: makeDate(2026, 3, 16, 9, 30), isAllDay: false, category: .toddlerActivity, city: "Irvine", address: "29 Hubble, Irvine, CA 92618", latitude: 33.6846, longitude: -117.8265, locationName: "Pretend City Children's Museum", imageURL: "https://upload.wikimedia.org/wikipedia/commons/6/60/Pretend-city-front.jpg", externalURL: "https://www.pretendcity.org/", isFeatured: false, isRecurring: true, tags: ["toddler", "indoor", "museum"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "toddler-town-mar23", title: "Toddler Town at Pretend City", eventDescription: "The museum opens just for toddlers ages 19 months to 3 years. Kids can climb, dance, problem-solve, and pretend through a miniature world supporting developmental milestones.", startDate: makeDate(2026, 3, 23, 8, 0), endDate: makeDate(2026, 3, 23, 9, 30), isAllDay: false, category: .toddlerActivity, city: "Irvine", address: "29 Hubble, Irvine, CA 92618", latitude: 33.6846, longitude: -117.8265, locationName: "Pretend City Children's Museum", imageURL: "https://upload.wikimedia.org/wikipedia/commons/6/60/Pretend-city-front.jpg", externalURL: "https://www.pretendcity.org/", isFeatured: false, isRecurring: true, tags: ["toddler", "indoor", "museum"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "baby-steps-mar3", title: "Baby Steps at Pretend City", eventDescription: "A special program for babies 0-18 months focusing on developmental milestones through music, movement, and socialization in a safe, stimulating space. Pre-registration required.", startDate: makeDate(2026, 3, 3, 8, 0), endDate: makeDate(2026, 3, 3, 9, 30), isAllDay: false, category: .toddlerActivity, city: "Irvine", address: "29 Hubble, Irvine, CA 92618", latitude: 33.6846, longitude: -117.8265, locationName: "Pretend City Children's Museum", imageURL: "https://upload.wikimedia.org/wikipedia/commons/6/60/Pretend-city-front.jpg", externalURL: "https://www.pretendcity.org/", isFeatured: false, isRecurring: true, tags: ["baby", "toddler", "indoor", "museum"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "carousel-mar3", title: "Free Carousel Ride - Toddlers & Tunes", eventDescription: "Complimentary Carousel and Giant Wheel rides, games, and an interactive DJ on the Giant Wheel Lawn. Designed for children ages 15 months through 5 years.", startDate: makeDate(2026, 3, 3, 10, 0), endDate: makeDate(2026, 3, 3, 12, 0), isAllDay: false, category: .toddlerActivity, city: "Irvine", address: "670 Spectrum Center Dr, Irvine, CA 92618", latitude: 33.6494, longitude: -117.7412, locationName: "Irvine Spectrum Center", imageURL: "https://www.irvinespectrumcenter.com/media/wiejtxev/carousel.jpg", externalURL: "https://www.irvinespectrumcenter.com/", isFeatured: true, isRecurring: true, tags: ["free", "toddler", "outdoor", "music"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "toddler-jump-mar5", title: "Toddler Jump and Play", eventDescription: "Indoor bounce house play time exclusively for toddlers and preschoolers. Soft play equipment, slides, and age-appropriate activities in a safe environment.", startDate: makeDate(2026, 3, 5, 10, 0), endDate: makeDate(2026, 3, 5, 12, 0), isAllDay: false, category: .toddlerActivity, city: "Mission Viejo", address: "27741 Crown Valley Pkwy, Mission Viejo, CA 92691", latitude: 33.5963, longitude: -117.6590, locationName: "Pump It Up", imageURL: "https://cdn.pumpitupparty.com/public-site-assets/PIU-SLIDER-1.jpg", externalURL: nil, isFeatured: false, isRecurring: true, tags: ["toddler", "indoor", "play"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        // MARK: Eco Tots

        Event(id: "ecotots-mar13", title: "Eco Tots at The Ecology Center", eventDescription: "A sensory, hands-on learning experience exploring the wonders of the garden for children up to 5 years old and their parents. Plant seeds, feed chickens, and explore nature.", startDate: makeDate(2026, 3, 13, 9, 0), endDate: makeDate(2026, 3, 13, 10, 30), isAllDay: false, category: .outdoorAdventure, city: "San Juan Capistrano", address: "32701 Alipaz St, San Juan Capistrano, CA 92675", latitude: 33.5017, longitude: -117.6628, locationName: "The Ecology Center", imageURL: "https://theecologycenter.org/wp-content/uploads/2022/12/Host_Evant_Desktop_Hero-1.jpg", externalURL: "https://theecologycenter.org/", isFeatured: false, isRecurring: true, tags: ["outdoor", "toddler", "nature", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "ecotots-mar20", title: "Eco Tots at The Ecology Center", eventDescription: "A sensory, hands-on learning experience exploring the wonders of the garden for children up to 5 years old and their parents. Plant seeds, feed chickens, and explore nature.", startDate: makeDate(2026, 3, 20, 9, 0), endDate: makeDate(2026, 3, 20, 10, 30), isAllDay: false, category: .outdoorAdventure, city: "San Juan Capistrano", address: "32701 Alipaz St, San Juan Capistrano, CA 92675", latitude: 33.5017, longitude: -117.6628, locationName: "The Ecology Center", imageURL: "https://theecologycenter.org/wp-content/uploads/2022/12/Host_Evant_Desktop_Hero-1.jpg", externalURL: "https://theecologycenter.org/", isFeatured: false, isRecurring: true, tags: ["outdoor", "toddler", "nature", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        // MARK: Farmers Markets

        Event(id: "fm-greatpark-mar1", title: "Great Park Certified Farmers Market", eventDescription: "Weekly certified farmers market featuring local produce, artisan goods, fresh food vendors, and family-friendly activities near the Great Park.", startDate: makeDate(2026, 3, 1, 10, 0), endDate: makeDate(2026, 3, 1, 14, 0), isAllDay: false, category: .farmersMarket, city: "Irvine", address: "100 Honors, Irvine, CA 92620", latitude: 33.6694, longitude: -117.7714, locationName: "Stonegate Elementary", imageURL: "https://cityofirvine.org/sites/default/files/styles/large_feature_image/public/EB-great%20park%20farmers%20market%20yoga%20april%202017-54_0.jpg?itok=MeALpC4z", externalURL: nil, isFeatured: false, isRecurring: true, tags: ["outdoor", "free", "food", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "fm-greatpark-mar8", title: "Great Park Certified Farmers Market", eventDescription: "Weekly certified farmers market featuring local produce, artisan goods, fresh food vendors, and family-friendly activities near the Great Park.", startDate: makeDate(2026, 3, 8, 10, 0), endDate: makeDate(2026, 3, 8, 14, 0), isAllDay: false, category: .farmersMarket, city: "Irvine", address: "100 Honors, Irvine, CA 92620", latitude: 33.6694, longitude: -117.7714, locationName: "Stonegate Elementary", imageURL: "https://cityofirvine.org/sites/default/files/styles/large_feature_image/public/EB-great%20park%20farmers%20market%20yoga%20april%202017-54_0.jpg?itok=MeALpC4z", externalURL: nil, isFeatured: false, isRecurring: true, tags: ["outdoor", "free", "food", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "fm-greatpark-mar15", title: "Great Park Certified Farmers Market", eventDescription: "Weekly certified farmers market featuring local produce, artisan goods, fresh food vendors, and family-friendly activities near the Great Park.", startDate: makeDate(2026, 3, 15, 10, 0), endDate: makeDate(2026, 3, 15, 14, 0), isAllDay: false, category: .farmersMarket, city: "Irvine", address: "100 Honors, Irvine, CA 92620", latitude: 33.6694, longitude: -117.7714, locationName: "Stonegate Elementary", imageURL: "https://cityofirvine.org/sites/default/files/styles/large_feature_image/public/EB-great%20park%20farmers%20market%20yoga%20april%202017-54_0.jpg?itok=MeALpC4z", externalURL: nil, isFeatured: false, isRecurring: true, tags: ["outdoor", "free", "food", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "fm-tustin-mar4", title: "Old Town Tustin Certified Farmers Market", eventDescription: "Year-round weekly farmers market in historic Old Town Tustin with approximately 40 vendors offering fresh produce, baked goods, and local artisan products.", startDate: makeDate(2026, 3, 4, 9, 0), endDate: makeDate(2026, 3, 4, 13, 0), isAllDay: false, category: .farmersMarket, city: "Tustin", address: "245 El Camino Real, Tustin, CA 92780", latitude: 33.7459, longitude: -117.8253, locationName: "Old Town Tustin", imageURL: "https://www.tustinca.org/ImageRepository/Document?documentId=19736", externalURL: nil, isFeatured: false, isRecurring: true, tags: ["outdoor", "free", "food"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "fm-tustin-mar11", title: "Old Town Tustin Certified Farmers Market", eventDescription: "Year-round weekly farmers market in historic Old Town Tustin with approximately 40 vendors offering fresh produce, baked goods, and local artisan products.", startDate: makeDate(2026, 3, 11, 9, 0), endDate: makeDate(2026, 3, 11, 13, 0), isAllDay: false, category: .farmersMarket, city: "Tustin", address: "245 El Camino Real, Tustin, CA 92780", latitude: 33.7459, longitude: -117.8253, locationName: "Old Town Tustin", imageURL: "https://www.tustinca.org/ImageRepository/Document?documentId=19736", externalURL: nil, isFeatured: false, isRecurring: true, tags: ["outdoor", "free", "food"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "scn-mar3", title: "Surf City Nights Street Fair & Farmers Market", eventDescription: "Weekly street fair and certified farmers market in downtown Huntington Beach with local produce, live entertainment, food vendors, and family activities along three blocks of Main Street.", startDate: makeDate(2026, 3, 3, 17, 0), endDate: makeDate(2026, 3, 3, 21, 0), isAllDay: false, category: .farmersMarket, city: "Huntington Beach", address: "Main St & PCH, Huntington Beach, CA 92648", latitude: 33.6553, longitude: -117.9992, locationName: "Downtown Huntington Beach", imageURL: "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,f_jpg,h_716,q_75,w_639/v1/clients/surfcityusa/QUw0Xeqb_72099ac2-5348-4aaf-8c11-f19d9daad045.jpg", externalURL: "https://www.hbdowntown.com/scn", isFeatured: false, isRecurring: true, tags: ["free", "outdoor", "food", "music"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "scn-mar10", title: "Surf City Nights Street Fair & Farmers Market", eventDescription: "Weekly street fair and certified farmers market in downtown Huntington Beach with local produce, live entertainment, food vendors, and family activities along three blocks of Main Street.", startDate: makeDate(2026, 3, 10, 17, 0), endDate: makeDate(2026, 3, 10, 21, 0), isAllDay: false, category: .farmersMarket, city: "Huntington Beach", address: "Main St & PCH, Huntington Beach, CA 92648", latitude: 33.6553, longitude: -117.9992, locationName: "Downtown Huntington Beach", imageURL: "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,f_jpg,h_716,q_75,w_639/v1/clients/surfcityusa/QUw0Xeqb_72099ac2-5348-4aaf-8c11-f19d9daad045.jpg", externalURL: "https://www.hbdowntown.com/scn", isFeatured: false, isRecurring: true, tags: ["free", "outdoor", "food", "music"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "farmakis-mar6", title: "Farmakis Farms Certified Farmers Market", eventDescription: "Family-friendly weekly farmers market with fresh produce, baked breads, artisanal cheeses, grass-fed beef, and handmade crafts in historic San Juan Capistrano.", startDate: makeDate(2026, 3, 6, 9, 0), endDate: makeDate(2026, 3, 6, 13, 0), isAllDay: false, category: .farmersMarket, city: "San Juan Capistrano", address: "29932 Camino Capistrano, San Juan Capistrano, CA 92675", latitude: 33.5010, longitude: -117.6625, locationName: "Farmakis Farms", imageURL: "https://images.squarespace-cdn.com/content/v1/613918d57efa26292f174222/317f6713-8be5-4dce-bb43-b79f4703185a/Barn+2.jpg", externalURL: "https://www.farmakisfarms.com/", isFeatured: false, isRecurring: true, tags: ["free", "outdoor", "food", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "farmakis-mar13", title: "Farmakis Farms Certified Farmers Market", eventDescription: "Family-friendly weekly farmers market with fresh produce, baked breads, artisanal cheeses, grass-fed beef, and handmade crafts in historic San Juan Capistrano.", startDate: makeDate(2026, 3, 13, 9, 0), endDate: makeDate(2026, 3, 13, 13, 0), isAllDay: false, category: .farmersMarket, city: "San Juan Capistrano", address: "29932 Camino Capistrano, San Juan Capistrano, CA 92675", latitude: 33.5010, longitude: -117.6625, locationName: "Farmakis Farms", imageURL: "https://images.squarespace-cdn.com/content/v1/613918d57efa26292f174222/317f6713-8be5-4dce-bb43-b79f4703185a/Barn+2.jpg", externalURL: "https://www.farmakisfarms.com/", isFeatured: false, isRecurring: true, tags: ["free", "outdoor", "food", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        // MARK: Storytime Events

        Event(id: "story-dp-mar3", title: "Toddler Story Time at Dana Point Library", eventDescription: "Stories, activities, and songs for children under 3 and their favorite adults. Stay and Play follows at 11:00 AM. Free, no registration required.", startDate: makeDate(2026, 3, 3, 10, 30), endDate: makeDate(2026, 3, 3, 11, 0), isAllDay: false, category: .storytime, city: "Dana Point", address: "33841 Niguel Rd, Dana Point, CA 92629", latitude: 33.4726, longitude: -117.6981, locationName: "Dana Point Library", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2025-09/IMG_0147.png?h=170501df&itok=1wLBFYkO", externalURL: "https://www.ocpl.org/", isFeatured: false, isRecurring: true, tags: ["free", "toddler", "library", "storytime"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "story-dp-mar10", title: "Toddler Story Time at Dana Point Library", eventDescription: "Stories, activities, and songs for children under 3 and their favorite adults. Stay and Play follows at 11:00 AM. Free, no registration required.", startDate: makeDate(2026, 3, 10, 10, 30), endDate: makeDate(2026, 3, 10, 11, 0), isAllDay: false, category: .storytime, city: "Dana Point", address: "33841 Niguel Rd, Dana Point, CA 92629", latitude: 33.4726, longitude: -117.6981, locationName: "Dana Point Library", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2025-09/IMG_0147.png?h=170501df&itok=1wLBFYkO", externalURL: "https://www.ocpl.org/", isFeatured: false, isRecurring: true, tags: ["free", "toddler", "library", "storytime"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "story-irv-mar5", title: "Preschool Storytime at Heritage Park Library", eventDescription: "Stories, songs, and activities for children ages 3-5 and their caregivers at Irvine Heritage Park Library.", startDate: makeDate(2026, 3, 5, 11, 0), endDate: makeDate(2026, 3, 5, 11, 30), isAllDay: false, category: .storytime, city: "Irvine", address: "14361 Yale Ave, Irvine, CA 92604", latitude: 33.6890, longitude: -117.7988, locationName: "Heritage Park Regional Library", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/ihp-2023.png", externalURL: "https://www.ocpl.org/", isFeatured: false, isRecurring: true, tags: ["free", "toddler", "library", "storytime"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "story-irv-mar12", title: "Preschool Storytime at Heritage Park Library", eventDescription: "Stories, songs, and activities for children ages 3-5 and their caregivers at Irvine Heritage Park Library.", startDate: makeDate(2026, 3, 12, 11, 0), endDate: makeDate(2026, 3, 12, 11, 30), isAllDay: false, category: .storytime, city: "Irvine", address: "14361 Yale Ave, Irvine, CA 92604", latitude: 33.6890, longitude: -117.7988, locationName: "Heritage Park Regional Library", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/ihp-2023.png", externalURL: "https://www.ocpl.org/", isFeatured: false, isRecurring: true, tags: ["free", "toddler", "library", "storytime"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "story-tus-mar7", title: "Storytime at Tustin Library", eventDescription: "Weekly storytime with picture books, songs, and activities for babies, toddlers, and preschoolers. Approximately 30 minutes.", startDate: makeDate(2026, 3, 7, 9, 0), endDate: makeDate(2026, 3, 7, 9, 30), isAllDay: false, category: .storytime, city: "Tustin", address: "345 E Main St, Tustin, CA 92780", latitude: 33.7458, longitude: -117.8253, locationName: "Tustin Library", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/tu-2023.png?h=ffdffee8&itok=VLv3jG40", externalURL: "https://www.ocpl.org/", isFeatured: false, isRecurring: true, tags: ["free", "toddler", "library", "storytime"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "story-tus-mar14", title: "Storytime at Tustin Library", eventDescription: "Weekly storytime with picture books, songs, and activities for babies, toddlers, and preschoolers. Approximately 30 minutes.", startDate: makeDate(2026, 3, 14, 9, 0), endDate: makeDate(2026, 3, 14, 9, 30), isAllDay: false, category: .storytime, city: "Tustin", address: "345 E Main St, Tustin, CA 92780", latitude: 33.7458, longitude: -117.8253, locationName: "Tustin Library", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/tu-2023.png?h=ffdffee8&itok=VLv3jG40", externalURL: "https://www.ocpl.org/", isFeatured: false, isRecurring: true, tags: ["free", "toddler", "library", "storytime"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "story-cm-mar5", title: "Family Storytime at Mesa Verde Library", eventDescription: "Stories, songs, and fingerplays for all ages at Mesa Verde Library in Costa Mesa. No registration required.", startDate: makeDate(2026, 3, 5, 11, 0), endDate: makeDate(2026, 3, 5, 11, 30), isAllDay: false, category: .storytime, city: "Costa Mesa", address: "2969 Mesa Verde Dr E, Costa Mesa, CA 92626", latitude: 33.6782, longitude: -117.8940, locationName: "Mesa Verde Library", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/cmmv-2023.png", externalURL: "https://www.ocpl.org/", isFeatured: false, isRecurring: true, tags: ["free", "family", "library", "storytime"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "bilingual-mar4", title: "Bilingual Family Storytime", eventDescription: "Bilingual storytime featuring books, songs, and movement in English and Spanish to help children develop early-literacy skills. Suggested for ages 0-5. Free, no registration required.", startDate: makeDate(2026, 3, 4, 10, 30), endDate: makeDate(2026, 3, 4, 11, 0), isAllDay: false, category: .storytime, city: "Tustin", address: "345 E Main St, Tustin, CA 92780", latitude: 33.7458, longitude: -117.8253, locationName: "Tustin Library", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/tu-2023.png?h=ffdffee8&itok=VLv3jG40", externalURL: "https://www.ocpl.org/", isFeatured: false, isRecurring: true, tags: ["free", "bilingual", "library", "storytime"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "drseuss", title: "Read Across America - Dr. Seuss Birthday", eventDescription: "National celebration of Dr. Seuss's birthday with Cat in the Hat storytime readings, themed crafts, and activities at libraries across Orange County.", startDate: makeDate(2026, 3, 2, 10, 0), endDate: makeDate(2026, 3, 2, 15, 0), isAllDay: false, category: .education, city: "Orange County", address: nil, latitude: 33.7175, longitude: -117.8311, locationName: "OC Public Libraries", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/ihp-2023.png", externalURL: "https://www.ocpl.org/", isFeatured: false, isRecurring: false, tags: ["free", "reading", "library", "kids"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        // MARK: Movies

        Event(id: "sensory-films-mar14", title: "AMC Sensory Friendly Family Films", eventDescription: "Family-friendly sensory screenings with lights turned up and sound turned down so kids can get up, dance, walk, shout, or sing. Shown at AMC Orange 30.", startDate: makeDate(2026, 3, 14, 10, 0), endDate: makeDate(2026, 3, 14, 12, 0), isAllDay: false, category: .freeMovie, city: "Orange", address: "20 City Blvd W, Orange, CA 92868", latitude: 33.7878, longitude: -117.8621, locationName: "AMC Orange 30", imageURL: "https://photos.cinematreasures.org/production/photos/358283/1636082910/large.JPG?1636082910", externalURL: "https://www.amctheatres.com/", isFeatured: false, isRecurring: true, tags: ["movie", "indoor", "kids", "sensory"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "sensory-films-mar28", title: "AMC Sensory Friendly Family Films", eventDescription: "Family-friendly sensory screenings with lights turned up and sound turned down so kids can get up, dance, walk, shout, or sing. Shown at AMC Orange 30.", startDate: makeDate(2026, 3, 28, 10, 0), endDate: makeDate(2026, 3, 28, 12, 0), isAllDay: false, category: .freeMovie, city: "Orange", address: "20 City Blvd W, Orange, CA 92868", latitude: 33.7878, longitude: -117.8621, locationName: "AMC Orange 30", imageURL: "https://photos.cinematreasures.org/production/photos/358283/1636082910/large.JPG?1636082910", externalURL: "https://www.amctheatres.com/", isFeatured: false, isRecurring: true, tags: ["movie", "indoor", "kids", "sensory"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "discount-movie-mar4", title: "AMC Discount Movie Day", eventDescription: "AMC Stubs members get 50% off tickets on Tuesdays and Wednesdays, bringing prices to around $6. Free Stubs Insider membership required.", startDate: makeDate(2026, 3, 4, 10, 0), endDate: makeDate(2026, 3, 4, 22, 0), isAllDay: false, category: .freeMovie, city: "Orange", address: "20 City Blvd W, Orange, CA 92868", latitude: 33.7878, longitude: -117.8621, locationName: "AMC Orange 30", imageURL: "https://photos.cinematreasures.org/production/photos/358283/1636082910/large.JPG?1636082910", externalURL: "https://www.amctheatres.com/", isFeatured: false, isRecurring: true, tags: ["discount", "movie", "indoor"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "free-movie-park", title: "Free Movie in the Park", eventDescription: "Bring your blankets and chairs for a free outdoor movie screening under the stars. Concessions available for purchase.", startDate: makeDate(2026, 3, 15, 18, 0), endDate: makeDate(2026, 3, 15, 21, 0), isAllDay: false, category: .freeMovie, city: "Huntington Beach", address: "7111 Talbert Ave, Huntington Beach, CA 92648", latitude: 33.6595, longitude: -117.9988, locationName: "Central Park", imageURL: "https://assets.simpleviewinc.com/simpleview/image/upload/v1573075654/clients/surfcityusa/DJI_0387_1__2a9cbdab-8c22-4a75-bc70-ff743394f11d.jpg", externalURL: nil, isFeatured: false, isRecurring: false, tags: ["free", "outdoor", "movie"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        // MARK: Arts & Crafts

        Event(id: "creativity-mar5", title: "Creativity Corner at HB Library", eventDescription: "Drop-in arts and crafts for children ages 4-12 at Huntington Beach Public Library. Create a new project each week with paint dotters, collage materials, paper art, and more. Free while supplies last.", startDate: makeDate(2026, 3, 5, 9, 30), endDate: makeDate(2026, 3, 5, 16, 30), isAllDay: false, category: .craft, city: "Huntington Beach", address: "525 Main St, Huntington Beach, CA 92648", latitude: 33.6611, longitude: -117.9988, locationName: "HB Main Street Library", imageURL: "https://www.huntingtonbeachca.gov/Images/Departments/Library/Hours%20and%20Locations/Hours/MainSt.BranchLibrary-12%20-%20Copy.jpg", externalURL: "https://hbpl.libcal.com/", isFeatured: false, isRecurring: true, tags: ["free", "craft", "kids", "library"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "creativity-mar12", title: "Creativity Corner at HB Library", eventDescription: "Drop-in arts and crafts for children ages 4-12 at Huntington Beach Public Library. Create a new project each week with paint dotters, collage materials, paper art, and more. Free while supplies last.", startDate: makeDate(2026, 3, 12, 9, 30), endDate: makeDate(2026, 3, 12, 16, 30), isAllDay: false, category: .craft, city: "Huntington Beach", address: "525 Main St, Huntington Beach, CA 92648", latitude: 33.6611, longitude: -117.9988, locationName: "HB Main Street Library", imageURL: "https://www.huntingtonbeachca.gov/Images/Departments/Library/Hours%20and%20Locations/Hours/MainSt.BranchLibrary-12%20-%20Copy.jpg", externalURL: "https://hbpl.libcal.com/", isFeatured: false, isRecurring: true, tags: ["free", "craft", "kids", "library"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "kids-craft-mar2", title: "Kids Craft All Day at Michaels", eventDescription: "Free craft activity for kids at Michaels. Different project each week including painting, beading, and seasonal crafts. All materials provided.", startDate: makeDate(2026, 3, 2, 10, 0), endDate: makeDate(2026, 3, 2, 16, 0), isAllDay: false, category: .craft, city: "Tustin", address: "2925 El Camino Real, Tustin, CA 92782", latitude: 33.7459, longitude: -117.8265, locationName: "Michaels", imageURL: "https://static.platform.michaels.com/pub/boredomPage/bannerdesk.webp", externalURL: "https://www.michaels.com/", isFeatured: false, isRecurring: true, tags: ["free", "craft", "kids"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "face-painting-mar3", title: "Free Face Painting at Irvine Spectrum", eventDescription: "Complimentary face painting for kids in the courtyard near the carousel. Professional face painters create butterflies, superheroes, and more.", startDate: makeDate(2026, 3, 3, 11, 0), endDate: makeDate(2026, 3, 3, 14, 0), isAllDay: false, category: .craft, city: "Irvine", address: "670 Spectrum Center Dr, Irvine, CA 92618", latitude: 33.6494, longitude: -117.7412, locationName: "Irvine Spectrum Center", imageURL: "https://www.irvinespectrumcenter.com/media/wiejtxev/carousel.jpg", externalURL: nil, isFeatured: false, isRecurring: true, tags: ["free", "kids", "outdoor"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        // MARK: Outdoor & Sports

        Event(id: "cars-coffee-mar7", title: "South OC Cars and Coffee", eventDescription: "The world's largest weekly car show featuring 1,000-3,000 vehicles including supercars, exotics, classics, and hot rods. Free admission, spectators welcome.", startDate: makeDate(2026, 3, 7, 9, 0), endDate: makeDate(2026, 3, 7, 11, 0), isAllDay: false, category: .outdoorAdventure, city: "San Clemente", address: "101 W Avenida Vista Hermosa, San Clemente, CA 92672", latitude: 33.4483, longitude: -117.6323, locationName: "Outlets at San Clemente", imageURL: "https://images.squarespace-cdn.com/content/v1/5a8b38504c0dbff0a1a687b1/33231edb-f558-47a5-88da-32524d19ec6b/Large+pano+shot+of+SOCCAC.jpg", externalURL: "https://www.southoccarsandcoffee.com/", isFeatured: false, isRecurring: true, tags: ["free", "outdoor", "cars", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "cars-coffee-mar14", title: "South OC Cars and Coffee", eventDescription: "The world's largest weekly car show featuring 1,000-3,000 vehicles including supercars, exotics, classics, and hot rods. Free admission, spectators welcome.", startDate: makeDate(2026, 3, 14, 9, 0), endDate: makeDate(2026, 3, 14, 11, 0), isAllDay: false, category: .outdoorAdventure, city: "San Clemente", address: "101 W Avenida Vista Hermosa, San Clemente, CA 92672", latitude: 33.4483, longitude: -117.6323, locationName: "Outlets at San Clemente", imageURL: "https://images.squarespace-cdn.com/content/v1/5a8b38504c0dbff0a1a687b1/33231edb-f558-47a5-88da-32524d19ec6b/Large+pano+shot+of+SOCCAC.jpg", externalURL: "https://www.southoccarsandcoffee.com/", isFeatured: false, isRecurring: true, tags: ["free", "outdoor", "cars", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "fire-station-mar13", title: "Fire Station Tour", eventDescription: "Free 30-minute guided fire station tour for families. Kids meet firefighters, see fire trucks, and learn fire safety. Requires scheduling 2 weeks in advance.", startDate: makeDate(2026, 3, 13, 10, 0), endDate: makeDate(2026, 3, 13, 10, 30), isAllDay: false, category: .fireStationTour, city: "Costa Mesa", address: "2300 Placentia Ave, Costa Mesa, CA 92627", latitude: 33.6632, longitude: -117.9035, locationName: "OCFA Fire Station #5", imageURL: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/DCFD_Engine_3.jpg/1280px-DCFD_Engine_3.jpg", externalURL: "https://www.ocfa.org/", isFeatured: false, isRecurring: true, tags: ["free", "educational", "outdoor"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "scooter-club-mar2", title: "Scooter Club at Great Park", eventDescription: "Kids scooter meetup at the Great Park. Bring your scooters and helmets for a fun ride with other families on the park's smooth paths.", startDate: makeDate(2026, 3, 2, 9, 0), endDate: makeDate(2026, 3, 2, 11, 0), isAllDay: false, category: .sports, city: "Irvine", address: "8000 Great Park Blvd, Irvine, CA 92618", latitude: 33.6694, longitude: -117.7714, locationName: "Great Park", imageURL: "https://cityofirvine.org/sites/default/files/styles/large_feature_image/public/EB-great%20park%20farmers%20market%20yoga%20april%202017-54_0.jpg?itok=MeALpC4z", externalURL: nil, isFeatured: false, isRecurring: true, tags: ["free", "outdoor", "kids", "sports"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        Event(id: "ice-skating", title: "Public Indoor Ice Skating", eventDescription: "Family-friendly public ice skating sessions. Skate rentals available. All ages and skill levels welcome.", startDate: makeDate(2026, 3, 1, 12, 0), endDate: makeDate(2026, 3, 1, 14, 0), isAllDay: false, category: .sports, city: "Anaheim", address: "300 W Lincoln Ave, Anaheim, CA 92805", latitude: 33.8353, longitude: -117.9145, locationName: "Anaheim ICE", imageURL: "https://www.therinks.com/media/5736/ai_newwrap_2025.jpg", externalURL: nil, isFeatured: false, isRecurring: true, tags: ["indoor", "sports", "family"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        // MARK: Subscriber Meetup

        Event(id: "coffee-mom-mar11", title: "Coffee & Mom Walk", eventDescription: "A casual meetup for moms to connect over coffee and a walk through scenic trails. A great way to socialize and get outdoors with your little ones.", startDate: makeDate(2026, 3, 11, 9, 0), endDate: makeDate(2026, 3, 11, 10, 30), isAllDay: false, category: .subscriberMeetup, city: "Irvine", address: "8000 Great Park Blvd, Irvine, CA 92618", latitude: 33.6694, longitude: -117.7714, locationName: "Great Park", imageURL: "https://cityofirvine.org/sites/default/files/styles/large_feature_image/public/EB-great%20park%20farmers%20market%20yoga%20april%202017-54_0.jpg?itok=MeALpC4z", externalURL: nil, isFeatured: false, isRecurring: true, tags: ["free", "outdoor", "mom", "social"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        // MARK: Music

        Event(id: "music-library-mar6", title: "Music at the Library", eventDescription: "Interactive music class for toddlers and preschoolers featuring songs, instruments, and movement. Free and open to all ages.", startDate: makeDate(2026, 3, 6, 10, 0), endDate: makeDate(2026, 3, 6, 10, 45), isAllDay: false, category: .music, city: "Lake Forest", address: "24562 Raymond Way, Lake Forest, CA 92630", latitude: 33.6469, longitude: -117.6890, locationName: "Lake Forest Library", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/ihp-2023.png", externalURL: "https://www.ocpl.org/", isFeatured: false, isRecurring: true, tags: ["free", "music", "toddler", "library"], metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),
    ]

    // MARK: - Sample Kids Eat Free Restaurants

    static let sampleRestaurants: [KidsEatFreeRestaurant] = [
        KidsEatFreeRestaurant(id: "r1", name: "Avila's El Ranchito", cities: ["Orange", "Laguna Niguel", "Lake Forest", "Foothill Ranch", "San Clemente", "Santa Ana"], dealDetails: "Orange, Lake Forest, Laguna Niguel: Kids eat free on Mondays from 4-10pm\nFoothill Ranch: Kids eat free on Sundays\nSan Clemente & Santa Ana: Kids eat free on Wednesdays 4-10pm", imageURL: "https://www.avilasorange.com/wp-content/uploads/2024/11/Orange-ext_HR-2-scaled-e1731021469280.jpg", websiteURL: "https://www.avilaselranchito.com", phoneNumber: "(714) 538-7180", address: "1132 N Tustin St, Orange, CA 92867", isActive: true, sortOrder: 0, metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        KidsEatFreeRestaurant(id: "r2", name: "BLK Earth Spirits", cities: ["Huntington Beach"], dealDetails: "Free Kids Breakfast on Saturdays and Sundays from 10am-1pm with the purchase of a qualifying adult entree.", imageURL: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/surfcityusa/BLK-Dining-3dd47ec85056a36_3dd47fe5-5056-a36a-0838cd8d023f4fec.jpg", websiteURL: "https://www.blkearthspirits.com", phoneNumber: "(714) 969-6400", address: "7628 Edinger Ave, Huntington Beach, CA 92647", isActive: true, sortOrder: 1, metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        KidsEatFreeRestaurant(id: "r3", name: "Denny's", cities: ["Tustin", "Santa Ana", "Anaheim"], dealDetails: "Santa Ana + Tustin: Kids eat free from 4-10pm every day with purchase of an adult meal.\nAnaheim 1610 Harbor Blvd: Kids eat free from 4-10pm every day.", imageURL: "https://www.dennys.com/sites/default/files/styles/full_width_sm/public/2024-11/1300x1300_DIG2115%20DCOM%20Dennys%20Sign_R2R.jpg", websiteURL: "https://www.dennys.com", phoneNumber: "(714) 730-5246", address: "13432 Newport Ave, Tustin, CA 92780", isActive: true, sortOrder: 2, metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        KidsEatFreeRestaurant(id: "r4", name: "IKEA", cities: ["Costa Mesa"], dealDetails: "Kids Eat Free on Wednesdays.\nKids Crafts on Wednesday evenings.", imageURL: "https://www.ikea.com/images/ikea-costa-mesa-store-front-b12443917f26629aa5edf1b9fe5877b9.jpg?f=s", websiteURL: "https://www.ikea.com/us/en/stores/costa-mesa/", phoneNumber: "(888) 888-4532", address: "1475 S Coast Dr, Costa Mesa, CA 92626", isActive: true, sortOrder: 3, metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        KidsEatFreeRestaurant(id: "r5", name: "Ruby's Diner", cities: ["Anaheim", "Brea", "Corona Del Mar", "Costa Mesa", "Laguna Beach", "San Clemente", "Santa Ana", "Tustin"], dealDetails: "Kids eat free on Tuesday nights from 4pm until close with purchase of adult entree.", imageURL: "https://rubys.b-cdn.net/dbcwp/wp-content/uploads/2022/11/balboa_desk_v2.jpg", websiteURL: "https://www.rubys.com", phoneNumber: "(949) 673-7829", address: "1 Balboa Pier, Newport Beach, CA 92661", isActive: true, sortOrder: 4, metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),
    ]

    // MARK: - Sample Parents Night Out Providers

    static let sampleProviders: [ParentsNightOutProvider] = [
        ParentsNightOutProvider(id: "p1", name: "Karate OC", cities: ["Fullerton", "Placentia"], providerDescription: "Games, Obstacle Courses, Laser Tag, Pizza, Drinks, and Movies! For ages 5+", ageRequirement: "Ages 5+", pricing: nil, schedule: "Monthly, Friday or Saturday evenings, 6:00–9:00 PM", promoCode: nil, promoDetails: nil, imageURL: "https://karateoc.com/wp-content/uploads/2021/01/DSC_1386-scaled.jpg", externalURL: "https://www.karateoc.com", isActive: true, sortOrder: 0, metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        ParentsNightOutProvider(id: "p2", name: "Valhallan Esports Lake Forest", cities: ["Lake Forest"], providerDescription: "These happen 2-3 times each month and include pizza, drinks, and a night of fun coached game play.", ageRequirement: nil, pricing: nil, schedule: "2–3 times per month, Friday or Saturday evenings", promoCode: "OCPG", promoDetails: "50% off parents night out!", imageURL: "https://arenas.valhallan.com/lake-forest-ca-us/wp-content/uploads/sites/16/2025/10/valhallan-arena-1024x1024-1.jpg", externalURL: "https://www.valhallanesports.com", isActive: true, sortOrder: 1, metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),

        ParentsNightOutProvider(id: "p3", name: "Sweet Peas Gymnastics", cities: ["Rancho Mission Viejo"], providerDescription: "Offered every Saturday night. Kids enjoy an evening of gymnastics, obstacle courses, trampolines, bounce houses, games, crafts, and more!", ageRequirement: "Ages 3-13, potty trained", pricing: "$27-$30", schedule: "Every Saturday, 5:30–9:00 PM", promoCode: nil, promoDetails: nil, imageURL: "https://sweetpeasgymnasticsrmv.com/wp-content/uploads/2021/11/about-rmv.jpg", externalURL: "https://www.sweetpeasgymnastics.com", isActive: true, sortOrder: 2, metro: "los-angeles", source: "preview", createdAt: Date(), modifiedAt: Date()),
    ]

    // MARK: - Sample About Sections

    static let sampleAboutSections: [AboutSection] = [
        AboutSection(id: "a1", text: "Hi, I'm Heather! I'm a South OC mom who started OCParentGuide on Instagram in 2021. My mission is to help families explore the local area by giving them curated recommendations for playgrounds, restaurants, library programs, travel destinations, and Orange County events.", imageURL: nil, imagePosition: .trailing, sortOrder: 0),
        AboutSection(id: "a2", text: "I created this website in 2023 because I felt like Instagram was getting just a little too small to fully showcase the resources and guides I've worked hard to create. My hope is that it will soon be a favorite go-to resource for you!", imageURL: nil, imagePosition: .leading, sortOrder: 1),
    ]

    // MARK: - Sample Resources

    static let sampleResources: [Resource] = [
        Resource(id: "res1", title: "Event Calendar Product Guide", fileURL: nil, thumbnailURL: nil, sortOrder: 0, createdAt: Date()),
    ]

    // MARK: - Helpers

    private static func makeDate(_ year: Int, _ month: Int, _ day: Int, _ hour: Int = 0, _ minute: Int = 0) -> Date {
        var components = DateComponents()
        components.year = year
        components.month = month
        components.day = day
        components.hour = hour
        components.minute = minute
        return Calendar.current.date(from: components)!
    }

    // MARK: - Real event data for month generation

    private struct EventTemplate {
        let title: String
        let description: String
        let category: EventCategory
        let city: String
        let address: String?
        let latitude: Double
        let longitude: Double
        let locationName: String?
        let externalURL: String?
        let imageURL: String?
        let tags: [String]
    }

    private static let eventTemplates: [EventTemplate] = [
        // Storytime
        EventTemplate(title: "Toddler Story Time", description: "Stories, activities, and songs for children under 3 and their favorite adults. Free, no registration required.", category: .storytime, city: "Dana Point", address: "33841 Niguel Rd, Dana Point, CA 92629", latitude: 33.4726, longitude: -117.6981, locationName: "Dana Point Library", externalURL: "https://www.ocpl.org/", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2025-09/IMG_0147.png?h=170501df&itok=1wLBFYkO", tags: ["free", "toddler", "library"]),
        EventTemplate(title: "Preschool Storytime", description: "Stories, songs, and activities for children ages 3-5 and their caregivers.", category: .storytime, city: "Irvine", address: "14361 Yale Ave, Irvine, CA 92604", latitude: 33.6890, longitude: -117.7988, locationName: "Heritage Park Regional Library", externalURL: "https://www.ocpl.org/", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/ihp-2023.png", tags: ["free", "toddler", "library"]),
        EventTemplate(title: "Family Storytime", description: "Stories, songs, and fingerplays for all ages. No registration required.", category: .storytime, city: "Costa Mesa", address: "2969 Mesa Verde Dr E, Costa Mesa, CA 92626", latitude: 33.6782, longitude: -117.8940, locationName: "Mesa Verde Library", externalURL: "https://www.ocpl.org/", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/cmmv-2023.png", tags: ["free", "family", "library"]),
        EventTemplate(title: "Bilingual Family Storytime", description: "Bilingual storytime in English and Spanish with books, songs, and movement for ages 0-5.", category: .storytime, city: "Tustin", address: "345 E Main St, Tustin, CA 92780", latitude: 33.7458, longitude: -117.8253, locationName: "Tustin Library", externalURL: "https://www.ocpl.org/", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/tu-2023.png?h=ffdffee8&itok=VLv3jG40", tags: ["free", "bilingual", "library"]),
        EventTemplate(title: "Tales and Trails Storytime", description: "Outdoor storytime adventure combining nature walks with picture books and songs.", category: .storytime, city: "Laguna Niguel", address: "30012 Crown Valley Pkwy, Laguna Niguel, CA 92677", latitude: 33.5325, longitude: -117.7076, locationName: "Crown Valley Park", externalURL: nil, imageURL: nil, tags: ["free", "outdoor", "storytime"]),

        // Farmers Market
        EventTemplate(title: "Farmers Market at Great Park", description: "Weekly certified farmers market featuring local produce, artisan goods, and family-friendly activities.", category: .farmersMarket, city: "Irvine", address: "100 Honors, Irvine, CA 92620", latitude: 33.6694, longitude: -117.7714, locationName: "Stonegate Elementary", externalURL: nil, imageURL: "https://cityofirvine.org/sites/default/files/styles/large_feature_image/public/EB-great%20park%20farmers%20market%20yoga%20april%202017-54_0.jpg?itok=MeALpC4z", tags: ["free", "outdoor", "food"]),
        EventTemplate(title: "Tustin Farmers Market", description: "Year-round farmers market in historic Old Town Tustin with 40+ vendors.", category: .farmersMarket, city: "Tustin", address: "245 El Camino Real, Tustin, CA 92780", latitude: 33.7459, longitude: -117.8253, locationName: "Old Town Tustin", externalURL: nil, imageURL: "https://www.tustinca.org/ImageRepository/Document?documentId=19736", tags: ["free", "outdoor", "food"]),
        EventTemplate(title: "Surf City Nights", description: "Street fair and farmers market in downtown Huntington Beach with live music and food vendors.", category: .farmersMarket, city: "Huntington Beach", address: "Main St, Huntington Beach, CA 92648", latitude: 33.6553, longitude: -117.9992, locationName: "Downtown HB", externalURL: "https://www.hbdowntown.com/scn", imageURL: "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,f_jpg,h_716,q_75,w_639/v1/clients/surfcityusa/QUw0Xeqb_72099ac2-5348-4aaf-8c11-f19d9daad045.jpg", tags: ["free", "outdoor", "food", "music"]),
        EventTemplate(title: "Farmakis Farms Farmers Market", description: "Family-friendly farmers market with fresh produce, artisanal cheeses, and handmade crafts.", category: .farmersMarket, city: "San Juan Capistrano", address: "29932 Camino Capistrano, San Juan Capistrano, CA 92675", latitude: 33.5010, longitude: -117.6625, locationName: "Farmakis Farms", externalURL: "https://www.farmakisfarms.com/", imageURL: "https://images.squarespace-cdn.com/content/v1/613918d57efa26292f174222/317f6713-8be5-4dce-bb43-b79f4703185a/Barn+2.jpg", tags: ["free", "outdoor", "food"]),

        // Toddler
        EventTemplate(title: "Toddler Town at Pretend City", description: "The museum opens just for toddlers ages 19 months to 3 years with climbing, dancing, and imaginative play.", category: .toddlerActivity, city: "Irvine", address: "29 Hubble, Irvine, CA 92618", latitude: 33.6846, longitude: -117.8265, locationName: "Pretend City", externalURL: "https://www.pretendcity.org/", imageURL: "https://upload.wikimedia.org/wikipedia/commons/6/60/Pretend-city-front.jpg", tags: ["toddler", "indoor", "museum"]),
        EventTemplate(title: "Baby Steps at Pretend City", description: "Program for babies 0-18 months focusing on developmental milestones through music and movement.", category: .toddlerActivity, city: "Irvine", address: "29 Hubble, Irvine, CA 92618", latitude: 33.6846, longitude: -117.8265, locationName: "Pretend City", externalURL: "https://www.pretendcity.org/", imageURL: "https://upload.wikimedia.org/wikipedia/commons/6/60/Pretend-city-front.jpg", tags: ["baby", "toddler", "indoor"]),
        EventTemplate(title: "Toddler Jump and Play", description: "Indoor bounce house play time exclusively for toddlers and preschoolers with age-appropriate activities.", category: .toddlerActivity, city: "Mission Viejo", address: "27741 Crown Valley Pkwy, Mission Viejo, CA 92691", latitude: 33.5963, longitude: -117.6590, locationName: "Pump It Up", externalURL: nil, imageURL: "https://cdn.pumpitupparty.com/public-site-assets/PIU-SLIDER-1.jpg", tags: ["toddler", "indoor", "play"]),
        EventTemplate(title: "Free Carousel Ride - Toddlers & Tunes", description: "Complimentary Carousel rides, games, and interactive DJ for children ages 15 months through 5 years.", category: .toddlerActivity, city: "Irvine", address: "670 Spectrum Center Dr, Irvine, CA 92618", latitude: 33.6494, longitude: -117.7412, locationName: "Irvine Spectrum Center", externalURL: "https://www.irvinespectrumcenter.com/", imageURL: "https://www.irvinespectrumcenter.com/media/wiejtxev/carousel.jpg", tags: ["free", "toddler", "outdoor"]),
        EventTemplate(title: "Kid Fit at Play & Grow", description: "Active play session for toddlers with obstacle courses, balance beams, and movement activities.", category: .toddlerActivity, city: "Laguna Niguel", address: "27401 Los Altos, Laguna Niguel, CA 92677", latitude: 33.5225, longitude: -117.7076, locationName: "Play & Grow", externalURL: nil, imageURL: nil, tags: ["toddler", "indoor", "sports"]),

        // Craft
        EventTemplate(title: "Kids Craft All Day at Michaels", description: "Free craft activity for kids. Different project each week with all materials provided.", category: .craft, city: "Tustin", address: "2925 El Camino Real, Tustin, CA 92782", latitude: 33.7459, longitude: -117.8265, locationName: "Michaels", externalURL: "https://www.michaels.com/", imageURL: "https://static.platform.michaels.com/pub/boredomPage/bannerdesk.webp", tags: ["free", "craft", "kids"]),
        EventTemplate(title: "Creativity Corner", description: "Drop-in arts and crafts for children ages 4-12 with paint, collage, and paper art.", category: .craft, city: "Huntington Beach", address: "525 Main St, Huntington Beach, CA 92648", latitude: 33.6611, longitude: -117.9988, locationName: "HB Main Street Library", externalURL: "https://hbpl.libcal.com/", imageURL: "https://www.huntingtonbeachca.gov/Images/Departments/Library/Hours%20and%20Locations/Hours/MainSt.BranchLibrary-12%20-%20Copy.jpg", tags: ["free", "craft", "kids", "library"]),
        EventTemplate(title: "Free Face Painting", description: "Complimentary face painting for kids with professional artists creating butterflies, superheroes, and more.", category: .craft, city: "Irvine", address: "670 Spectrum Center Dr, Irvine, CA 92618", latitude: 33.6494, longitude: -117.7412, locationName: "Irvine Spectrum Center", externalURL: nil, imageURL: "https://www.irvinespectrumcenter.com/media/wiejtxev/carousel.jpg", tags: ["free", "kids", "outdoor"]),
        EventTemplate(title: "Take-Home Craft at the Library", description: "Pick up a free craft kit to make at home. New theme each week. Available while supplies last.", category: .craft, city: "Lake Forest", address: "24562 Raymond Way, Lake Forest, CA 92630", latitude: 33.6469, longitude: -117.6890, locationName: "Lake Forest Library", externalURL: "https://www.ocpl.org/", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/ihp-2023.png", tags: ["free", "craft", "library"]),
        EventTemplate(title: "Cardboard Class", description: "Build amazing creations from recycled cardboard boxes. Tape, markers, and decorations provided.", category: .craft, city: "Orange", address: "101 N Center St, Orange, CA 92866", latitude: 33.7878, longitude: -117.8531, locationName: "Orange Public Library", externalURL: nil, imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/ihp-2023.png", tags: ["free", "craft", "kids"]),

        // Museum/Science
        EventTemplate(title: "Discovery Cube Exploration", description: "Hands-on science exhibits and interactive experiences for curious young minds.", category: .museum, city: "Santa Ana", address: "2500 N Main St, Santa Ana, CA 92705", latitude: 33.7455, longitude: -117.8677, locationName: "Discovery Cube OC", externalURL: "https://www.discoverycube.org/", imageURL: "https://www.discoverycube.org/wp-content/uploads/2026/02/G-9494-DCOC-Bubblefest-Homepage-Banners-2-1.jpg", tags: ["science", "indoor", "museum"]),
        EventTemplate(title: "Pretend City Discovery Day", description: "Half-price admission. Explore 17 interconnected rooms designed for kids to learn through play.", category: .museum, city: "Irvine", address: "29 Hubble, Irvine, CA 92618", latitude: 33.6846, longitude: -117.8265, locationName: "Pretend City", externalURL: "https://www.pretendcity.org/", imageURL: "https://upload.wikimedia.org/wikipedia/commons/6/60/Pretend-city-front.jpg", tags: ["discount", "indoor", "museum"]),

        // Movies
        EventTemplate(title: "Free Movie with Popcorn", description: "Free family movie screening with complimentary popcorn. Bring the whole family!", category: .freeMovie, city: "Huntington Beach", address: "7111 Talbert Ave, Huntington Beach, CA 92648", latitude: 33.6595, longitude: -117.9988, locationName: "Central Park", externalURL: nil, imageURL: "https://assets.simpleviewinc.com/simpleview/image/upload/v1573075654/clients/surfcityusa/DJI_0387_1__2a9cbdab-8c22-4a75-bc70-ff743394f11d.jpg", tags: ["free", "outdoor", "movie"]),
        EventTemplate(title: "$6 Movie Day", description: "Discounted movie tickets at AMC for Stubs members. Great deal for family movie outings.", category: .freeMovie, city: "Orange", address: "20 City Blvd W, Orange, CA 92868", latitude: 33.7878, longitude: -117.8621, locationName: "AMC Orange 30", externalURL: "https://www.amctheatres.com/", imageURL: "https://photos.cinematreasures.org/production/photos/358283/1636082910/large.JPG?1636082910", tags: ["discount", "movie", "indoor"]),

        // Food
        EventTemplate(title: "Chick-Fil-A Play Date", description: "Casual play date at Chick-fil-A with indoor playground while enjoying lunch.", category: .food, city: "Irvine", address: "13682 Jamboree Rd, Irvine, CA 92602", latitude: 33.6973, longitude: -117.7990, locationName: "Chick-fil-A", externalURL: "https://www.chick-fil-a.com/", imageURL: "https://upload.wikimedia.org/wikipedia/commons/9/98/Restaurant_Chick-Fil-A_in_Sugar_House_SLC.JPG", tags: ["food", "indoor", "toddler"]),
        EventTemplate(title: "Breakfast on the Farm", description: "Farm-fresh breakfast experience for families with fresh eggs, pancakes, and farm animal interactions.", category: .food, city: "San Juan Capistrano", address: "29932 Camino Capistrano, San Juan Capistrano, CA 92675", latitude: 33.5010, longitude: -117.6625, locationName: "Farmakis Farms", externalURL: "https://www.farmakisfarms.com/", imageURL: "https://images.squarespace-cdn.com/content/v1/613918d57efa26292f174222/317f6713-8be5-4dce-bb43-b79f4703185a/Barn+2.jpg", tags: ["food", "outdoor", "farm"]),

        // Outdoor
        EventTemplate(title: "Cars and Coffee", description: "Weekly car show featuring supercars, exotics, classics, and hot rods. Free admission.", category: .outdoorAdventure, city: "San Clemente", address: "101 W Avenida Vista Hermosa, San Clemente, CA 92672", latitude: 33.4483, longitude: -117.6323, locationName: "Outlets at San Clemente", externalURL: "https://www.southoccarsandcoffee.com/", imageURL: "https://images.squarespace-cdn.com/content/v1/5a8b38504c0dbff0a1a687b1/33231edb-f558-47a5-88da-32524d19ec6b/Large+pano+shot+of+SOCCAC.jpg", tags: ["free", "outdoor", "cars"]),
        EventTemplate(title: "Eco Tots at The Ecology Center", description: "Sensory hands-on garden experience for children up to 5 years old and their parents.", category: .outdoorAdventure, city: "San Juan Capistrano", address: "32701 Alipaz St, San Juan Capistrano, CA 92675", latitude: 33.5017, longitude: -117.6628, locationName: "The Ecology Center", externalURL: "https://theecologycenter.org/", imageURL: "https://theecologycenter.org/wp-content/uploads/2022/12/Host_Evant_Desktop_Hero-1.jpg", tags: ["outdoor", "toddler", "nature"]),

        // Sports
        EventTemplate(title: "Scooter Club at Great Park", description: "Kids scooter meetup at the Great Park. Bring scooters and helmets for a fun ride.", category: .sports, city: "Irvine", address: "8000 Great Park Blvd, Irvine, CA 92618", latitude: 33.6694, longitude: -117.7714, locationName: "Great Park", externalURL: nil, imageURL: "https://cityofirvine.org/sites/default/files/styles/large_feature_image/public/EB-great%20park%20farmers%20market%20yoga%20april%202017-54_0.jpg?itok=MeALpC4z", tags: ["free", "outdoor", "kids"]),
        EventTemplate(title: "Public Indoor Ice Skating", description: "Family-friendly public ice skating sessions. Skate rentals available.", category: .sports, city: "Anaheim", address: "300 W Lincoln Ave, Anaheim, CA 92805", latitude: 33.8353, longitude: -117.9145, locationName: "Anaheim ICE", externalURL: nil, imageURL: "https://www.therinks.com/media/5736/ai_newwrap_2025.jpg", tags: ["indoor", "sports", "family"]),

        // Education
        EventTemplate(title: "Kindergarten Readiness", description: "Free program helping kids prepare for kindergarten with letters, numbers, and social skills.", category: .education, city: "Irvine", address: "14361 Yale Ave, Irvine, CA 92604", latitude: 33.6890, longitude: -117.7988, locationName: "Heritage Park Library", externalURL: "https://www.ocpl.org/", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/ihp-2023.png", tags: ["free", "education", "kids"]),
        EventTemplate(title: "Spanish Family Storytime", description: "Spanish-language storytime with books, songs, and activities for families.", category: .education, city: "Santa Ana", address: "26 Civic Center Plaza, Santa Ana, CA 92701", latitude: 33.7495, longitude: -117.8680, locationName: "Santa Ana Library", externalURL: "https://www.santa-ana.org/library/", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/ihp-2023.png", tags: ["free", "spanish", "library"]),

        // Fire Station
        EventTemplate(title: "Fire Station Tour", description: "Free guided tour. Meet firefighters, see trucks, and learn fire safety.", category: .fireStationTour, city: "Costa Mesa", address: "2300 Placentia Ave, Costa Mesa, CA 92627", latitude: 33.6632, longitude: -117.9035, locationName: "OCFA Fire Station #5", externalURL: "https://www.ocfa.org/", imageURL: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/DCFD_Engine_3.jpg/1280px-DCFD_Engine_3.jpg", tags: ["free", "educational"]),

        // Music
        EventTemplate(title: "Music at the Library", description: "Interactive music class for toddlers with songs, instruments, and movement.", category: .music, city: "Lake Forest", address: "24562 Raymond Way, Lake Forest, CA 92630", latitude: 33.6469, longitude: -117.6890, locationName: "Lake Forest Library", externalURL: "https://www.ocpl.org/", imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/ihp-2023.png", tags: ["free", "music", "toddler"]),
        EventTemplate(title: "Storytime & Pancakes", description: "Storytime combined with free pancakes for kids. A delicious way to enjoy stories together.", category: .music, city: "Newport Beach", address: "1000 Avocado Ave, Newport Beach, CA 92660", latitude: 33.6189, longitude: -117.8770, locationName: "Newport Beach Library", externalURL: nil, imageURL: "https://www.ocpl.org/sites/ocpl/files/styles/landscape_560/public/2023-04/ihp-2023.png", tags: ["free", "storytime", "food"]),

        // Subscriber
        EventTemplate(title: "Coffee & Mom Walk", description: "Casual meetup for moms to connect over coffee and a scenic walk with the kids.", category: .subscriberMeetup, city: "Irvine", address: "8000 Great Park Blvd, Irvine, CA 92618", latitude: 33.6694, longitude: -117.7714, locationName: "Great Park", externalURL: nil, imageURL: "https://cityofirvine.org/sites/default/files/styles/large_feature_image/public/EB-great%20park%20farmers%20market%20yoga%20april%202017-54_0.jpg?itok=MeALpC4z", tags: ["free", "outdoor", "mom"]),
        EventTemplate(title: "Miss Stefanie's Dance Class", description: "Free outdoor dance class for toddlers and preschoolers led by Miss Stefanie.", category: .subscriberMeetup, city: "Irvine", address: "1 Civic Center Plaza, Irvine, CA 92606", latitude: 33.6846, longitude: -117.8265, locationName: "Irvine Civic Center", externalURL: nil, imageURL: nil, tags: ["free", "outdoor", "dance", "toddler"]),
    ]

    /// Generate realistic events for a given month using real OC event data
    static func generateMonthEvents(for date: Date) -> [Event] {
        let calendar = Calendar.current
        let daysInMonth = date.daysInMonth
        let startOfMonth = date.startOfMonth
        var events: [Event] = []

        for day in 1...daysInMonth {
            let eventDate = calendar.date(byAdding: .day, value: day - 1, to: startOfMonth)!
            let eventsForDay = Int.random(in: 12...30)

            for i in 0..<eventsForDay {
                let template = eventTemplates[Int.random(in: 0..<eventTemplates.count)]
                let hour = Int.random(in: 8...18)
                let minute = [0, 15, 30].randomElement()!
                let startTime = calendar.date(bySettingHour: hour, minute: minute, second: 0, of: eventDate)!
                let duration = Int.random(in: 1...3)
                let endTime = calendar.date(byAdding: .hour, value: duration, to: startTime)!
                let event = Event(
                    id: "gen-\(day)-\(i)",
                    title: template.title,
                    eventDescription: template.description,
                    startDate: startTime,
                    endDate: endTime,
                    isAllDay: i == 0 && Bool.random(),
                    category: template.category,
                    city: template.city,
                    address: template.address,
                    latitude: template.latitude,
                    longitude: template.longitude,
                    locationName: template.locationName,
                    imageURL: template.imageURL,
                    externalURL: template.externalURL,
                    isFeatured: i == 0,
                    isRecurring: true,
                    tags: template.tags,
                    metro: "los-angeles",
                    source: "preview",
                    createdAt: Date(),
                    modifiedAt: Date()
                )
                events.append(event)
            }
        }
        return events
    }
}
